Feat/mfa
juanjiTech/jTerm-proto pull request #8
Opened 2023-10-09 10:55 UTC by GoldenSheep402

先解决TOTP

2023-10-10 05:07 UTC, asjdf commented on proto/auth/v1/auth_service.proto
> +message DisableEmailMFARequest {
disable是不是直接算作是高风险操作，然后需要验证之类的再操作即可，不一定要邮箱验证吧

2023-10-10 05:43 UTC, GoldenSheep402 commented on proto/auth/v1/auth_service.proto
> +message EnableTOTPRequest {
改了，一个AddTOTP，添加进去一个TOTP（假如已有未激活的覆盖掉，即只允许有一个not active的数据存在，假如已有active的则不允许操作），响应返回密钥，在数据库内表示为not active，一个ActiveTOTP,激活已导入的TOTP

2023-10-10 05:48 UTC, GoldenSheep402 commented on proto/auth/v1/auth_service.proto
> +message DisableEmailMFARequest {
这个我想的是用来移除指定邮箱，加了两个字段totp_code和primayr_email_code，用户任选一种方式进行身份验证，这样合适吗

2023-10-10 05:48 UTC, GoldenSheep402 commented on proto/auth/v1/auth_service.proto
> +  string code_old_email = 3;
确实 好像不是很必要

2023-10-10 05:57 UTC, GoldenSheep402 commented on proto/auth/v1/auth_service.proto
> +  rpc AddTOTP(AddTOTPRequest) returns (AddTOTPResponse) {
AddTOTP，把新生成的添加到数据库，标注为not active，然后返回密钥和恢复码，在ActiveTOP中提交一个Code，如果通过则设置为active,而且AddTOTP不允许在有active记录时添加而且只允许一个not active的存在，已有not active的则用新数据覆盖掉它

2023-10-10 07:30 UTC, asjdf commented
我感觉我们先捋一下思路？这里主要有邮箱验证和TFA验证两种。我们之所以要获取TFA的码是因为我们要确认用户安装/登记TFA的流程没有问题，能够通过服务器的验证。也就是说，我们不需要关心用户TFASecret的正确性，只需要保证前端那边传过来的用户输入的TFA码能对上TFASecret即可。实际上TFASecret在第一次绑定的时候可以由前端提供，因为这不影响绑定后的安全性。

而用户如果要走邮箱验证，直接走就好了，因为用户已经完成了邮箱的绑定，也就是说已经验证过邮箱的归属权了，感觉不太有必要再次验证了。用户可以选他所有已经绑定过的邮箱作为MFA邮箱，且这个选择应该是在用户需要MFA的时候自行选择。

我们所要做的应该是：
1. 提供一个TFA的绑定机制
2. 在进行MFA时给用户提供一个选择MFA渠道的方式
3. 提供MFA渠道设置的方式。（比如是否使用邮箱/手机作为MFA渠道

2023-10-10 07:55 UTC, GoldenSheep402 commented
1.绑定机制的话，对于TOTP我的思路是这样，Add的时候在数据库中存入未激活的数据（已经与用户绑定），然后Active的时候将其启用。然后Email确定所有权后可以添加到备用邮箱中，用户可以自己切换主邮箱。
2.在进行MFA时给用户提供一个选择MFA渠道的方式 ：通过status获取到mfa状态，从这个里面去选。
3.提供MFA渠道设置的方式。 注册的时候的邮箱直接作为MFA的email渠道的主邮箱，添加TOTP需要通过email的认证。

2023-10-10 08:06 UTC, asjdf commented
hummm，我不是说这个机制不可行，主要想表达的意思是有没有必要这么做，比如针对你提出的第一点，用户在进行绑定的时候，我们只需要让前端提供TFAsecret和TFACode就好了。one shot即可完成。

然后就是邮箱的问题，邮箱绑定和启用邮箱2FA是两个分离的需求，启用邮箱2FA依赖于邮箱绑定。

第二点和我理解的一样

第三点和我理解的也差不多，我们不妨更抽象一点来看这个操作。我们之所以需要做email验证，实际上是在提升回话权限，也就是将当前会话提升至sudo模式。那么实际上可以拆分成两个步骤了，第一步，通过MFA临时提升账号权限；第二步，做TFA绑定

2023-10-10 09:52 UTC, asjdf commented
我晚上re

2023-10-10 10:52 UTC, asjdf requested changes

2023-10-10 10:52 UTC, asjdf commented on proto/auth/v1/auth_service.proto
> +  EmailStatus email_status = 2;
这个是不是可以repeat？因为所有的绑定邮箱应该都可以用？

2023-10-10 10:52 UTC, asjdf commented on proto/auth/v1/auth_service.proto
> +message DisableEmailMFARequest {
这个点应该在下午的沟通中已经解释清楚了x，就sudo模式执行高风险操作

2023-10-10 10:52 UTC, asjdf commented on proto/auth/v1/auth_service.proto
> +message GetAccountStatusResponse{
可以在proto里头直接丢注释，gen的时候丢到代码和swagger里头

2023-10-10 11:02 UTC, GoldenSheep402 commented on proto/auth/v1/auth_service.proto
> +  EmailStatus email_status = 2;
确实 没注意到

2023-10-10 11:10 UTC, GoldenSheep402 commented on proto/auth/v1/auth_service.proto
> +message GetAccountStatusResponse{
嗯，那sudo模式可以在redis中存入UID+:sudo_expire_at:+sudo失效时间(类似于这样的)，然后看失效时间是否到达区分可以吗。

2023-10-11 14:50 UTC, asjdf requested changes
ci好像被误动到了

2023-10-11 15:02 UTC, asjdf approved these changes
LGTM ❤️

合分支用squash吧，中间commit好多

2023-10-11 15:05 UTC, merged